### PR TITLE
network.py line1 updated

### PR DESCRIPTION
**Pull request by gauravssnl**
error in 1st line  corrected.
from x import (y,z) does not work on PyS60.
so,correct working syntax is:
from x import y,z

### CODE REVIEW

**Comment by simon816** [comment]
Firstly, wow Symbian and PyS60 is still in use today?

At time of upload to github, this application did work. I'm pretty sure it was built for PyS60 2.0.0 which is built on Python 2.5, compared to the older release of PyS60 1.4.5 built on Python 2.2. You can find PyS60 2.0.0 here: https://garage.maemo.org/frs/?group_id=854

This project is pretty much "read only" in that I am not updating or supporting it (note that I may push more code that was written years ago just to publish my old work).

**Comment by gauravssnl** [comment]
No,that will not work on both versions of PyS60.I tested on both.OK.So,I made corrections.
Yeah,I use both Symbian and Android.I  also write PyS60 scripts but I ain't expert like you .Aren't you available on twitter or Facebook???

**Comment by gauravssnl** [comment]
No reply ???

**Comment by simon816** [comment]
Sorry, I don't see this as a priority since I am not maintaining anything on this repository.
You can use my code and make modifications to it for private use, but I won't accept this PR on this occasion.

You can contact me at me@simon816.com

**Comment by gauravssnl** [comment]
it is ok.I just wanted to show proof  with screenshots.it is your wish,because it's your code not mine.I do not know much .

**Comment by gauravssnl** [comment]
Thanks for your scripts.I really like it

**Pull request closed without merging**
